### ISSUE TITLE
Still valid? 401 response.

### ISSUE THREAD

**Issue by ambitionphp** [AeonLucid/MusicallyRE#1]
Anybody have positive results with this? I get 401 error when trying to login however this is my first time using C#. I'm in the process of porting to PHP. I got a 401 error from my PHP code so I set up visual studio to test the C# code which gave me a 401 response as well.

**Comment by ambitionphp** [comment]
My fault. I'll keep you updated on PHP port.

**Comment by AeonLucid** [comment]
Goodluck!
